---
slug: 'asynchronous'
title: 'Javascript asynchronous'
tags: ['Javascript', 'project']
date: '2024-12-13'
description: '자바스크립트 비동기처리 이해하기'
thumbnail: ''
---

## Promise

ES6 이전의 자바스크립트는 비동기처리를 위해 콜백함수를 사용했다. 하지만 그러한 방식은 비동기처리가 많아질 수록 깊이가 깊어져, 콜백지옥을 만드는 문제점이 있다.

이를 개선한 것이 Promise 함수다.

#### How to use Promise

```JS
const myPromise = new Promise((resolve, reject) => {
  // 구현..
})
```

promise 호출은 성공할 수도, 실패할 수도 있다. resolve는 성공한 경우, reject는 실패한 경우다.

원래 같으면 콜백지옥이 되는 코드를 이렇게 바꿀 수 있다.

```JS
function increaseAndPrint(n) {
  return new Promise((resolve, reject) => {
	//구현기능(API호출 등)
    setTimeout(() => {
      const value = n + 1;
      if (value === 5) {
        const error = new Error();
        error.name = 'ValueIsFiveError';
        reject(error); //error는 reject로 처리
        return;
      }
      console.log(value);
      resolve(value); //success는 resolve로 처리
    }, 1000);
  });
}

increaseAndPrint(0)
  .then(increaseAndPrint)
  .then(increaseAndPrint)
  .then(increaseAndPrint)
  .then(increaseAndPrint)
  .then(increaseAndPrint)
  .catch(e => {
    console.error(e);
  });
```

좀 더 깊이 들어가면, promise 생성자가 포함하는 함수는 실행함수(시간이 걸리고 처리해야 하는 함수) 이다. 그리고 그 실행함수 안에 resolve 와 reject 함수도 포함되어 있다.

Promise 생성자는 promise 객체를 반환한다. promise 객체에는 크게 state, result 변수가 담겨있다.

- state - 처음엔 "pending(보류)"이었다가, resolve(성공한 경우)가 호출되면 "fullfilled", reject(실패한 경우)가 호출되면 "rejected"로 상태가 바뀐다.
- result - 처음엔 "undefined"이었다가, resolve(value)가 호출되면 value로, reject(error)가 호출되면 error 로 바뀐다. 결과를 저장하는 프로퍼티다

+참고로 실패한 경우 new Error() 생성자를 통해 에러 객체를 상속받고 그걸로 에러처리를 해줘야 한다.

Promise 단점: 디버깅힘듦, 데이터공유될 시 처리 힘듦

## then, catch, finally

#### then

결과(성공, 실패)를 반환하는 메서드다.
첫번째 인자는 성공한 경우 - result
두번째 인자는 실패한 경우 - error

```JS
promise.then(
	console.log(result) //성공한 경우
	console.log(error) //실패한 경우
)
```

성공한 경우만 다루고 싶다면 인자를 하나만 넣으면 된다(첫번째 인자)

```JS
const promise => () => {
	//함수정의
}

promise.then(function(result) {
  console.log(result);
});
```

#### catch

실패한 경우만 다루고 싶다면 catch를 사용한다.

사실은 then 메서드의 첫번째 인자가 성공한 경우이기 때문에, 첫번째 인자를 null 로 처리하고 then을 쓰는거랑 같다.

```JS
promise.then(null, errorHandlerFunction) {
	console.log(errorHandlerFunction);
}
```

```JS
promise.catch(function(error) => {
	console.log(error);
})
```

#### finally

Promise의 결과가 어떻든 종료되었는지 여부를 검사

```JS
new Promise((resolve, rejecct) => {
	//시간이 걸리는 로직
}).finally(()=>{로딩 바 없애기})
	.then(result => console.log(result));
	.catch(error => console.log(error));
```

### References

- [Promise, async/await 참고자료](https://learnjs.vlpt.us/async/)
- [Promise 자세히다루기](https://ko.javascript.info/promise-basics)
